#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
  path:     /login_check
  methods: [POST]

easy_admin_bundle:
  resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  prefix: /admin
  type: annotation